name: Test backend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Copy .env file
        run: cp sample.env .env
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: ./backend
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev --directory ./backend
      - name: Run tests
        run: uv run --directory ./backend pytest
